---
abstract: "<One-line description of module's purpose>"
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  Mojolicious::Lite: 0
  Test::More: 0
  Test::NoWarnings: 0
  WWW::Mechanize: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: W3C-SOAP-WADL
provides:
  W3C::SOAP::WADL:
    file: lib/W3C/SOAP/WADL.pm
    version: v0.0.1
  W3C::SOAP::WADL::Document:
    file: lib/W3C/SOAP/WADL/Document.pm
    version: v0.0.1
  W3C::SOAP::WADL::Document::Doc:
    file: lib/W3C/SOAP/WADL/Document/Doc.pm
    version: v0.0.1
  W3C::SOAP::WADL::Document::Grammars:
    file: lib/W3C/SOAP/WADL/Document/Grammars.pm
    version: v0.0.1
  W3C::SOAP::WADL::Document::Link:
    file: lib/W3C/SOAP/WADL/Document/Link.pm
    version: v0.0.1
  W3C::SOAP::WADL::Document::Method:
    file: lib/W3C/SOAP/WADL/Document/Method.pm
    version: v0.0.1
  W3C::SOAP::WADL::Document::Node:
    file: lib/W3C/SOAP/WADL/Document/Node.pm
    version: v0.0.7
  W3C::SOAP::WADL::Document::Option:
    file: lib/W3C/SOAP/WADL/Document/Option.pm
    version: v0.0.1
  W3C::SOAP::WADL::Document::Param:
    file: lib/W3C/SOAP/WADL/Document/Param.pm
    version: v0.0.1
  W3C::SOAP::WADL::Document::Representation:
    file: lib/W3C/SOAP/WADL/Document/Representation.pm
    version: v0.0.1
  W3C::SOAP::WADL::Document::Request:
    file: lib/W3C/SOAP/WADL/Document/Request.pm
    version: v0.0.1
  W3C::SOAP::WADL::Document::Resource:
    file: lib/W3C/SOAP/WADL/Document/Resource.pm
    version: v0.0.1
  W3C::SOAP::WADL::Document::ResourceType:
    file: lib/W3C/SOAP/WADL/Document/ResourceType.pm
    version: v0.0.1
  W3C::SOAP::WADL::Document::Resources:
    file: lib/W3C/SOAP/WADL/Document/Resources.pm
    version: v0.0.1
  W3C::SOAP::WADL::Document::Response:
    file: lib/W3C/SOAP/WADL/Document/Response.pm
    version: v0.0.1
  W3C::SOAP::WADL::Element:
    file: lib/W3C/SOAP/WADL/Element.pm
    version: v0.0.1
  W3C::SOAP::WADL::Meta::Method:
    file: lib/W3C/SOAP/WADL/Meta/Method.pm
    version: v0.0.7
  W3C::SOAP::WADL::Node:
    file: lib/W3C/SOAP/WADL/Node.pm
    version: v0.0.1
  W3C::SOAP::WADL::Parser:
    file: lib/W3C/SOAP/WADL/Parser.pm
    version: v0.0.1
  W3C::SOAP::WADL::Traits:
    file: lib/W3C/SOAP/WADL/Traits.pm
    version: v0.0.1
  W3C::SOAP::WADL::Utils:
    file: lib/W3C/SOAP/WADL/Utils.pm
    version: v0.0.1
recommends:
  Pod::Coverage: 0
  Test::Kwalitee: 0
  Test::Perl::Critic: 0
  Test::Spelling: 0
requires:
  File::ShareDir: 1.00
  JSON: 0
  List::Util: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Types::Moose: 0
  Path::Class: 0
  Scalar::Util: 0
  Template: 0
  TryCatch: 0
  W3C::SOAP::Utils: 0.001000
  W3C::SOAP::XSD: 0.001000
  XML::Rabbit: 0
  XML::Rabbit::Root: 0
  perl: 5.006
  version: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=W3C::SOAP::WADL
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ivanwills/W3C-SOAP-WADL.git
version: v0.0.1
